---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian
    image: docker.io/pycontribs/debian
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
